### ISSUE TITLE
Incorporate unit testing into project for current health-check route and corresponding controller

### ISSUE THREAD

**Issue by anthony-jackman** [established-1907/prometheus#23]
Resource 1: https://rrawat.com/blog/unit-test-express-api
Resource 2: https://github.com/kennie-larkson/node-api-unit-test
Resource 3: https://dev.to/demetrakopetros/unit-testing-node-js-apis-c2k
Resource 4: https://github.com/InfoDevkota/NodeJS-API-Unit-Testing

**Comment by EnergeticPixels** [comment]
@anthony-jackman I believe that Node-Tap would serve this API better for route and controller testing.  Comes with its own visual code coverage.  And through fastify-inject (inherent in fastify), we dont have to constantly spin up the server but we can directly inject route destinations.  What you think?

**Comment by anthony-jackman** [comment]
> @anthony-jackman I believe that Node-Tap would serve this API better for route and controller testing. Comes with its own visual code coverage. And through fastify-inject (inherent in fastify), we dont have to constantly spin up the server but we can directly inject route destinations. What you think?

Sounds like a plan.  I will change the title of this issue number.  We will figure out how to do reportable code coverage in another issue ticket.
